version: '3'


services:
  postgresql:
    image: postgres:12
    container_name: catalogage-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=catalogage
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdata:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  pgdata:
