# Python is installed via pyenv, which sets the `python` executable accordingly to
# the installed Python version via the bash profile.
# But Ansible does not run commands as a user by default, so we must get
# the actual path to the binary using this pattern.
# See: https://stackoverflow.com/a/58744872
- name: Get Python binary path
  shell: bash -ilc 'which python'
  register: which_python
- name: Set python_bin_path fact
  set_fact:
    python_bin_path: "{{ which_python.stdout | trim() }}"

- name: Ensure Python dependencies are installed
  # This installs / synchronizes Python dependencies, ensuring we use a venv.
  pip:
    chdir: "{{ workdir }}"
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_command: "{{ python_bin_path }} -m venv"
    state: present
  become: true
