"""rename_url_to_url

Revision ID: b3dac4035ce9
Revises: e951f6fd7fbf
Create Date: 2022-07-06 15:09:52.582476

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3dac4035ce9"
down_revision = "e951f6fd7fbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "published_url", new_column_name="url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "url", new_column_name="published_url")
    # ### end Alembic commands ###
