"""add-password-token-auth

Revision ID: bf5d3d51d4f0
Revises: d24cec0c6ddd
Create Date: 2022-01-03 13:50:40.325518

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf5d3d51d4f0"
down_revision = "d24cec0c6ddd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.add_column("user", sa.Column("password_hash", sa.String(), nullable=False))
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    op.drop_column("user", "password_hash")
    op.drop_table("token")
    # ### end Alembic commands ###
