name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: catalogage
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      APP_DATABASE_URL: "postgresql+asyncpg://username:password@localhost:5432/catalogage"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install dependencies"
        run: make install

      - name: "Build"
        run: make build

      - name: "Run migrations"
        run: make migrate

      - name: "Run checks"
        run: make check

      - name: "Run tests"
        run: make test-ci
