name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"

      - name: "Install dependencies"
        run: make install

      - name: "Run checks"
        run: make check

      - name: "Run tests"
        run: make test
